Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2022
Var
// Seção de Declarações das variáveis 
a,b,c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreval("Escreva o valor de A e B sendo C=30")
     leia(a,b)
     se (a>15) ou (b>15) entao
     escreval ("A+B é maior que C!")
     fimse


Fimalgoritmo