Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2022
Var
// Seção de Declarações das variáveis 
nI:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        escreval("Informe o número")
        leia (nI)
          se (nI mod 2=0)entao
          escreval (nI," É par!")
        senao
           escreval (nI," É impar!")
         fimse


Fimalgoritmo