Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/07/2022
Var
// Seção de Declarações das variáveis 
    nome:caracter;
    idade:inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
          idade:=5
           escreva("refri"+"do":idade)
           

           

Fimalgoritmo